# Generated by Django 5.2 on 2025-05-31 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='img',
            field=models.ImageField(unique=True, upload_to='upload/product/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
