# Generated by Django 5.2 on 2025-05-31 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20250531_2335'),
    ]

    operations = [
    ]
