# Generated by Django 5.2 on 2025-07-06 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='تصویر پروفایل')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='آدرس کامل')),
                ('location_lat', models.FloatField(blank=True, null=True, verbose_name='عرض جغرافیایی')),
                ('location_lng', models.FloatField(blank=True, null=True, verbose_name='طول جغرافیایی')),
                ('location_name', models.CharField(blank=True, max_length=100, verbose_name='نام مکان')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل کاربر',
                'verbose_name_plural': 'پروفایل کاربران',
            },
        ),
    ]
