# Generated by Django 5.2 on 2025-07-07 23:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0004_remove_userprofile_geolocation_userprofile_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='تصویر پروفایل'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان آدرس')),
                ('full_address', models.TextField(verbose_name='آدرس کامل')),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(25.0), django.core.validators.MaxValueValidator(40.0)], verbose_name='عرض جغرافیایی')),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(44.0), django.core.validators.MaxValueValidator(64.0)], verbose_name='طول جغرافیایی')),
                ('is_default', models.BooleanField(default=False, verbose_name='آدرس پیش\u200cفرض')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='محله')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'آدرس تحویل',
                'verbose_name_plural': 'آدرس\u200cهای تحویل',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
