# Generated by Django 5.2 on 2025-07-08 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0008_user_remove_userprofile_user_delete_useraddress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
