# Generated by Django 5.2 on 2025-07-08 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0009_remove_user_email_remove_user_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
