# Generated by Django 5.2 on 2025-07-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_dashboard', '0010_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userpicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
            ],
        ),
    ]
